name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.4]
        laravel: [^7.0]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ hashFiles('composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, fileinfo, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist --classmap-authoritative --optimize-autoloader

      - name: Prepare Laravel application
        run: |
          cp .env.github .env
          php artisan --version
          php artisan key:generate
          php artisan package:discover

      - name: Install NPM dependencies
        run: yarn install

      - name: Compile assets
        run: yarn run production

      - name: Execute tests
        run: vendor/bin/phpunit

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: curl -X POST ${{ secrets.DEPLOYMENT_HOOK_URL }}
